/* Bilingual dictionary (RU / EN) */
const I18N = {
  ru: {
    'nav.education':'Образование','nav.work':'Опыт','nav.awards':'Грамоты','nav.events':'Мероприятия','nav.gallery':'Галерея','nav.contact':'Контакты',
    'hero.title':'Вычислительная гидродинамика','hero.subtitle':'Тепломассообмен · Гидродинамика · Моделирование','hero.cta':'Запросить встречу по симуляции',
    'edu.title':'Образование',
    'edu.1':'2008 – 2013  Бакалавр общей механики «диплом с отличием», университет Дамаска, Дамаск, Сирия.',
    'edu.2':'2013 – 2015  Магистр теплотехники, университет Дамаска, Дамаск, Сирия.',
    'edu.3':'2016 – 2018  Магистр теплофизики и теплоэнергетики «диплом с отличием», МЭИ, Москва, Россия.',
    'edu.4':'2018 – 2022  Аспирант теплофизики и теоретической теплотехники, МЭИ, Москва, Россия.',
    'edu.5':'2023  Кандидат технический наук — теплофизика и теоретическая теплотехника, МЭИ, Москва, Россия.',
    'work.title':'Опыт работы',
    'work.pos1':'Ассистент — Университет Дамаска, Дамаск, Сирия',
    'work.pos1.i1':'Экспериментальные и численные исследования (EES, ANSYS, MathCad, MATLAB, AutoCAD).',
    'work.pos1.i2':'Расчёты/лабораторные работы по тепломассопереносу, гидродинамике, турбинам, охлаждению, отоплению и кондиционированию.',
    'work.pos2':'Ассистент — МЭИ, Москва, Россия',
    'work.pos3':'Старший преподаватель — МЭИ, Москва, Россия',
    'work.pos3.i1':'Лабораторные занятия по «Тепломассообмен и гидродинамика» (бакалавры и магистры).',
    'work.pos3.i2':'Консультирование курсовых работ по «Тепломассообмен и гидродинамика».',
    'work.pos3.i3':'Обучение выполнению расчётов в ANSYS.',
    'work.pos4':'Реализация некоторых практических проектов (Мосэнерго, Красный котельщик).',
    'work.pos5':'Рецензент 16 журналов (Physics of Fluids, International Journal of Heat and Mass Transfer и др.).',
    'work.pos6':'Инженер 2 категории — МЭИ, Москва, Россия.',
    'work.pos7':'Главный специалист CFD моделирования — Научно-исследовательский и проектный институт карбамида, Москва, Россия.',
    'work.interests.title':'Некоторые из моих экспериментальных и численных интересов:',
    'work.i1':'Тепломассообмен','work.i2':'Гидродинамика','work.i3':'Ламинарные течения','work.i4':'Турбулентные течения (завихрения)','work.i5':'Серфинг (Surfing)','work.i6':'Разработка теплообменников','work.i7':'Испытание на прочность','work.i8':'Воздушные винты (самолёты)','work.i9':'2D и 3D моделирование','work.i10':'Горение','work.i11':'Стационарные и нестационарные задачи','work.i12':'Однофазные и двухфазные системы','work.i13':'Масштабирование реактора с перемешивающим устройством','work.i14':'Эжекторы и инжекторы','work.i15':'Фарсунки',
    'awards.title':'Почетные грамоты',
    'awards.1':'Пять дипломов Баселя Аль-асада лучшему выпускнику (2008–2013, Университет Дамаска).',
    'awards.2':'Благодарственное письмо и грамота за отличную учёбу в магистратуре (2018, МЭИ).',
    'awards.3':'Четыре диплома I/II степени, МНТК «Радиоэлектроника, электротехника и энергетика» (2019–2021, МЭИ).',
    'awards.4':'Две грамоты за III место в конкурсе стихов, Олимпиада по РКИ (2018–2019, МЭИ).',
    'awards.5':'Диплом III степени, II Международная онлайн-олимпиада по РКИ (2020, СПбГУ).',
    'awards.6':'Диплом II степени, IV Международная онлайн-олимпиада по РКИ (2023, СПбГУ).',
    'awards.7':'Награда Президента Сирии за выдающиеся публикации (2023, Сирия).',
    'events.title':'Участие в научных и культурных мероприятиях',
    'events.1':'Участие в международных научных конференциях (2016 – по настоящее время).',
    'events.2':'Международный форум по энергоэффективности «Российская энергетическая неделя» (2017, Москва, Россия).',
    'events.3':'Выставка «Культура моей страны (Сирии)» (2017–2019, МЭИ).',
    'events.4':'Культурный конкурс «Лучшее национальное блюдо» (2018, МЭИ).',
    'events.5':'Обучающий курс по дисциплине «Физика» для ресурсных центров РФ за рубежом (2020, частная школа «Аль-Ассея», Дамаск).',
    'events.6':'Проведение онлайн-курсов по 20+ предметам (2020 – по настоящее время).',
    'gallery.title':'Галерея',
    'contact.title':'Контакты','contact.text':'Интересует сотрудничество или встреча для обсуждения симуляции?','contact.cta':'Написать письмо'
  },
  en: {
    'nav.education':'Education','nav.work':'Experience','nav.awards':'Honors','nav.events':'Events','nav.gallery':'Gallery','nav.contact':'Contact',
    'hero.title':'Computational Fluid Dynamics','hero.subtitle':'Heat & Mass Transfer · Fluid Dynamics · Simulation','hero.cta':'Request a Simulation Meeting',
    'edu.title':'Education',
    'edu.1':'2008–2013 B.Sc. in General Mechanics (with distinction), Damascus University, Damascus, Syria.',
    'edu.2':'2013–2015 M.Sc. in Heat Engineering, Damascus University, Damascus, Syria.',
    'edu.3':'2016–2018 M.Sc. in Thermophysics & Power Engineering (with distinction), MPEI, Moscow, Russia.',
    'edu.4':'2018–2022 Ph.D. studies in Thermophysics & Theoretical Heat Engineering, MPEI, Moscow, Russia.',
    'edu.5':'2023 Candidate of Technical Sciences — Thermophysics & Theoretical Heat Engineering, MPEI, Moscow, Russia.',
    'work.title':'Work Experience',
    'work.pos1':'Teaching Assistant — Damascus University, Damascus, Syria',
    'work.pos1.i1':'Experimental and numerical studies (EES, ANSYS, MathCad, MATLAB, AutoCAD).',
    'work.pos1.i2':'Calculations/labs on heat & mass transfer, fluid dynamics, gas/steam turbines, HVAC.',
    'work.pos2':'Teaching Assistant — MPEI, Moscow, Russia',
    'work.pos3':'Senior Lecturer — MPEI, Moscow, Russia',
    'work.pos3.i1':'Lab classes in Heat & Mass Transfer and Fluid Dynamics (B.Sc./M.Sc.).',
    'work.pos3.i2':'Coursework supervision in Heat & Mass Transfer and Fluid Dynamics.',
    'work.pos3.i3':'Training students to perform ANSYS simulations.',
    'work.pos4':'Implementation of practical projects (Mosenergo, Krasny Kotelshchik).',
    'work.pos5':'Reviewer for 16 journals (Physics of Fluids, International Journal of Heat and Mass Transfer, etc.).',
    'work.pos6':'Engineer (2nd category) — MPEI, Moscow, Russia.',
    'work.pos7':'Chief CFD Specialist — Research & Design Institute of Urea, Moscow, Russia.',
    'work.interests.title':'Selected experimental & numerical interests:',
    'work.i1':'Heat & Mass Transfer','work.i2':'Fluid Dynamics','work.i3':'Laminar Flows','work.i4':'Turbulent Flows (Vortices)','work.i5':'Surfing','work.i6':'Heat Exchanger Design','work.i7':'Strength Testing','work.i8':'Air Propellers (Aircraft)','work.i9':'2D & 3D Modeling','work.i10':'Combustion','work.i11':'Steady & Unsteady Problems','work.i12':'Single- & Two-Phase Systems','work.i13':'Scaling of Stirred Reactors','work.i14':'Ejectors & Injectors','work.i15':'Atomizers/Nozzles',
    'awards.title':'Honors & Awards',
    'awards.1':'Five Basil al-Assad awards for top graduate (2008–2013, Damascus University).',
    'awards.2':'Letter of appreciation & merit certificate for excellent M.Sc. studies (2018, MPEI).',
    'awards.3':'Four diplomas (I & II degree), Intl. Sci-Tech Conference “Radio Electronics, Electrical & Power Engineering” (2019–2021, MPEI).',
    'awards.4':'Two diplomas for 3rd place in poetry contest, Russian Language Olympiad for internationals (2018–2019, MPEI).',
    'awards.5':'3rd-degree diploma, II Intl. Online Olympiad in Russian as a Foreign Language (2020, SPbU).',
    'awards.6':'2nd-degree diploma, IV Intl. Online Olympiad in Russian as a Foreign Language (2023, SPbU).',
    'awards.7':'President of Syria Award for outstanding 2023 publications (2023, Syria).',
    'events.title':'Participation in Scientific & Cultural Events',
    'events.1':'International scientific conferences (2016–present).',
    'events.2':'Russian Energy Week, International Forum on Energy Efficiency (2017, Moscow).',
    'events.3':'Exhibition “The Culture of My Country (Syria)” (2017–2019, MPEI).',
    'events.4':'Cultural contest “Best National (Syrian) Dish” (2018, MPEI).',
    'events.5':'Training course (on/offline) for Russian education resource centers abroad — “Physics”, basic level (2020, Al-Asseya Private School, Damascus).',
    'events.6':'Online courses on 20+ subjects (2020–present).',
    'gallery.title':'Gallery',
    'contact.title':'Contact','contact.text':'Interested in collaboration or a simulation meeting?','contact.cta':'Email Me'
  }
};

function switchLang(lang){
  const dict = I18N[lang] || I18N.ru;
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    const key = el.getAttribute('data-i18n');
    if (dict[key]) el.textContent = dict[key];
  });
  localStorage.setItem('lang', lang);
}
